test_upper_case_names (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_upper_case_names (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 17, in test_upper_case_names
    output = list(map(exercice.majuscule, self.words))
  File "/home/runner/work/chapitre-02-MaelPixel/chapitre-02-MaelPixel/exercice.py", line 5, in majuscule
    ord(chr(mot))-32
TypeError: an integer is required (got type str)

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
